# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: foundation-component-audit
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: foundation-component-audit
#   template:
#     metadata:
#       labels:
#         app: foundation-component-audit
#       annotations:
#         gke-gcsfuse/volumes: "true"
#     spec:
#       serviceAccountName: foundation-component-service-account
#       imagePullSecrets:
#         - name: artifact-registry-secret
#       containers:
#         - name:  foundation-component-audit-container
#           image: europe-docker.pkg.dev/playpen-e16de4/main/amazoncorretto:17-alpine
#           env:
#             - name: DB_NAME
#               value: postgres
#             - name: DB_HOST
#               value: 127.0.0.1
#             - name: DB_USER
#               value: admin
#             - name: DB_PASS
#               value: admin
#           volumeMounts:
#           - name: gcs-fuse-csi-pv
#             mountPath: /app
#             readOnly: true
#           command: ["java", "-jar", "/app/foundation-component-audit-0.0.1-SNAPSHOT.jar"]

#         - name: cloud-sql-proxy
#           image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
#           command: [ "/cloud-sql-proxy", "playpen-e16de4:europe-west1:postgresql-primary"]
#       volumes:
#       - name: gcs-fuse-csi-pv
#         persistentVolumeClaim:
#           claimName: gcs-fuse-csi-static-pvc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundation-component-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundation-component-audit
  template:
    metadata:
      labels:
        app: foundation-component-audit
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: foundation-component-service-account
      imagePullSecrets:
        - name: artifact-registry-secret
      containers:
        - name: foundation-component-audit-container
          image: europe-docker.pkg.dev/playpen-e16de4/main/amazoncorretto:17-alpine
          env:
            - name: DB_NAME
              value: postgres
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_USER
              value: admin
            - name: DB_PASS
              value: admin
          volumeMounts:
            - name: gcs-fuse-csi-pv
              mountPath: /shared
              readOnly: true
          command: ["sh", "-c", "ls "]
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
          command: ["/cloud-sql-proxy", "playpen-e16de4:europe-west1:postgresql-primary"]
      volumes:
        - name: gcs-fuse-csi-pv
          persistentVolumeClaim:
            claimName: gcs-fuse-csi-static-pvc
