# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: gcs-fuse-csi-pv
# spec:
#   accessModes:
#   - ReadWriteMany
#   capacity:
#     storage: 5Gi
#   storageClassName: gcs-storage-class
#   claimRef:
#     namespace: staging
#     name: gcs-fuse-csi-static-pvc 
#   mountOptions:
#     - only-dir= / #It mounts relative path of bucket i.e gcsfuse-checkers/test
#   csi:
#     driver: gcsfuse.csi.storage.gke.io
#     volumeHandle: playpen-e16de4-lib-bucket
#     readOnly: true

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: gcs-storage-class
  mountOptions:
    - only-dir=/
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: playpen-e16de4-lib-bucket
    readOnly: true

