output "kubeconfig" {
  value = <<EOT
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUxNdXBiOGNSd0FnUVpwakFOSUNKTDB3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa01EQmxNbUZrTldFdFl6WXdNaTAwWWpNMUxXRTBaVFV0WkRabE9UWTFaVEEyWWpWawpNQ0FYRFRJME1Ea3dNekExTXprME5Gb1lEekl3TlRRd09ESTNNRFl6T1RRMFdqQXZNUzB3S3dZRFZRUURFeVF3Ck1HVXlZV1ExWVMxak5qQXlMVFJpTXpVdFlUUmxOUzFrTm1VNU5qVmxNRFppTldRd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDeHJISlhsY0crWXdGMExTT1FaaStFN2twdzVPa0pHemxJNXIvQwp3ams0ZGJMdkF1WW9iWWtWUTllRGFnWmx4aGhVNDB6Y2p3d0tlUWtESFVIUDg4OVEwMjQxRjBnSXV6dmgrM1BaClBFUlBITFVnY3ptT2syYlJnQWh4anM1SkYvMHh2Wi9pRXlrUEJpL09Hb0tVY2RJRTR6cXFMUjBsNm05OG9LZ1cKYnYrQjd0aUlYdFJtb09XWHRQaGlOVlJPYXpFRTNkTWhrdGRzWXVZeTI5aURBcEJzUHZvd0hJZDZoYVlHb3NRdQpVZDJqdDBlY1ZUN2s0em5LWEc2V1ptWlNITzNKOGRBVnQ0LzRaYysxTzAxOHhuWC9mMzd2dndrSHdER0pTaGFlCkg5alFVdFQ2SVkyNlIxY08yN2NrbUgwcVp4aURsZkw2bkxXVThZakFoVkIwOU9qTFhPWnhuNWJqdFNJWnVvQmgKV09aUVpOY2NGUTBTWWlPVmhaZWxYNFUxemhJQlB5djcxVE5TRDRqOHo0UVY5TlBQT2dPWFZ0OHJVbWk5YkY2MApkL25TZEVMV1g2VWhEVDcxYzl4Rk5vTElUeUtDbmhyV2VId1RiM0p0REg0WVJRSzNFV3BhajFXeGZzcHBGUDdoCkxIVDdkcU0wMERRTEw5NjU0NWdkektyTDlzTUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGRDZ4eldiTnRWNlViMlZpM3dSaFQyUy9NRGxWTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQmtyMDVJbUJoS1VaTXNHczdSbHc1aXhlajhiUHZEbVM5V0FlRXUzR1FCCkZ4cGtGdENWWnhGRGxyb1J4REZ3QjhWMWJaZ0Z3SlJmd0dGOXdkYmtiZlB5bytaWFFZZEl1UHBsMU1GUy9RMCsKakRGWVlCTWp0WHFrcjM3VmpoMndQWElRTkFmSXVZb1RvL1B4THYvQjFGOXdBeC9TS0ZraE9wZEhnQnNPeDlFOApUYVhRYmJDTmpEdS9kL2pUZTlmTEhtRXk3UHhBeml3SzhZYmNncmhKSHgxNEV0dGZzTCtpdy9JQnZ3OW1HYVY2CkhnNExlRlZNNG13bGdMMVVKTUU2WngwQ01KYlJ5RnpFNytIcTJzeXp1OVpnNFMyaVQ2YzVmZmFNSGlBTTJGNFgKS3YzYTZyOVQvS3paVHQyZ1RBN25rcXNXT3dXZWIrbHFoMzlTcjhkV3l0WXU2dWV5NUNaUzFKdkU0bmJlbjBUSgpFbFBlSWdVQ0k2YnExeWEzL0EwOGwxVkN2ZzU4a0dRanNzbzJ4SFIwTUZLODFrVk9VZ09UMGZHTE1uRTR6UWwvCmVYcHVTQmwyemgyUnViZlJsc1oxUzVGWCt6WGgxYU9hNStMbUdHdmlZL0xNdnFZemYwZDZhSGZ4N2VvcWlnNnAKeVJKZlkwaFc4aGtSYmZXQlI0bHIyYzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.79.237.237
  name: gke_playpen-e16de4_europe-west1_playpen-e16de4-gke
contexts:
- context:
    cluster: gke_playpen-e16de4_europe-west1_playpen-e16de4-gke
    user: gke_playpen-e16de4_europe-west1_playpen-e16de4-gke
  name: gke_playpen-e16de4_europe-west1_playpen-e16de4-gke
current-context: gke_playpen-e16de4_europe-west1_playpen-e16de4-gke
kind: Config
preferences: {}
users:
- name: gke_playpen-e16de4_europe-west1_playpen-e16de4-gke
  user:
    apiVersion: client.authentication.k8s.io/v1beta1
    command: gke-gcloud-auth-plugin
    installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
      https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
    provideClusterInfo: true
EOT
sensitive = true
}