apiVersion: v1
kind: ConfigMap
metadata:
  name: foundation-component-audit-config
data:
  foundation_component_audit_project_id: "playpen-795065"
  foundation_component_audit_region: "europe-west1"
  foundation_component-dataproc-cluster-name: "dp-cluster"
  foundation_component_kafka_url: "your-kafka-url"
  foundation_component_audit_db_url: "jdbc:postgresql://10.246.0.3:5432/postgres"
  foundation_component_audit_db_user: "audit-user"
  foundation_component_audit_db_password: "abcdefgh"